# Utilise l'image SDK complète pour pouvoir exécuter 'dotnet watch run'
FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app


RUN echo '#!/bin/sh\nfind /app -type d \\( -name "bin" -o -name "obj" \\) -exec rm -rf {} + 2>/dev/null || true' > /clean.sh && chmod +x /clean.sh

# Définit le port que Kestrel utilisera à l'intérieur du conteneur
ENV ASPNETCORE_URLS=http://+:8080 
EXPOSE 8080

# Configure le ENTRYPOINT pour qu'il attende la commande de l'hôte
ENTRYPOINT ["dotnet"]
