# Utilise l'image SDK complète pour pouvoir exécuter 'dotnet watch run'
FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS dev

# --- Ajout des dépendances manquantes pour Alpine ---
# NopCommerce utilise des librairies de traitement d'images et de globalisation
RUN apk add --no-cache icu-libs icu-data-full libc-dev tzdata gcompat

# Installation des paquets graphiques nécessaires pour NopCommerce (comme dans votre Dockerfile original)
RUN apk add tiff --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/main/ --allow-untrusted
RUN apk add libgdiplus --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted

WORKDIR /app

# Définit le port que Kestrel utilisera à l'intérieur du conteneur
ENV ASPNETCORE_URLS=http://+:8080 
EXPOSE 8080

# Configure le ENTRYPOINT pour qu'il attende la commande de l'hôte
ENTRYPOINT ["dotnet"]
